const input = document.getElementById("userInput");
const sendBtn = document.getElementById("sendBtn");
const chatArea = document.getElementById("chatArea");

let messages = [
  {
    role: "system",
    content: `
You are NovaHoyaAI.
Created and owned by itzlootdev.

You are NOT ChatGPT.
You are NOT developed by OpenAI.

Your Development Name is NovaCreations.

Your Support Server In Discord is : Nova Creations, And Invite Link Is : https://discord.gg/kxyFtrh9Ya

Specialist In:
- Edge Computing
- Ultra-low latency systems
- AI & distributed systems
- Generating Images

Main CEO Of You:
 Afsal
 Ahzan 
 Ammar

If the user has Pro, add "NovaHoyaAI Pro 🔥" flair in some replies.
    `
  }
];

let isPro = false;
let imageCount = 0;
let messageCount = 0;

const MAX_IMAGES_FREE = 5;
const MAX_MESSAGES_FREE = 25;

// Load saved data from localStorage
function loadSavedData() {
  const saved = localStorage.getItem("novaHoyaAI_data");
  if (saved) {
    const data = JSON.parse(saved);
    isPro = data.isPro || false;
    imageCount = data.imageCount || 0;
    messageCount = data.messageCount || 0;

    if (data.messages) {
      data.messages.forEach(msg => {
        // Re-create message divs
        const div = document.createElement("div");
        div.className = `message ${msg.type}`;
        div.innerHTML = msg.content;
        chatArea.appendChild(div);
      });
      chatArea.scrollTop = chatArea.scrollHeight;
    }
  }
  updateProStatus();
}
loadSavedData();

// Save everything to localStorage
function saveData() {
  const chatMessages = [];
  document.querySelectorAll('.message').forEach(div => {
    chatMessages.push({
      content: div.innerHTML,
      type: div.classList.contains('user') ? 'user' : 'bot'
    });
  });

  localStorage.setItem("novaHoyaAI_data", JSON.stringify({
    isPro,
    imageCount,
    messageCount,
    messages: chatMessages
  }));
}

// Update header with Pro status or limits
function updateProStatus() {
  let header = document.querySelector('header');
  let statusDiv = document.getElementById('pro-status');
  if (!statusDiv) {
    statusDiv = document.createElement('div');
    statusDiv.id = "pro-status";
    header.appendChild(statusDiv);
  }

  if (isPro) {
    statusDiv.innerHTML = `
      <div style="margin-top: 15px; text-align: center;">
        <span style="background: linear-gradient(135deg, #FFD700, #FFA500); color: black; padding: 8px 20px; border-radius: 30px; font-weight: bold; font-size: 18px;">
          NovaHoyaAI Pro 🔥 UNLIMITED
        </span>
        <p style="margin-top: 8px; font-size: 13px; color: #888;">Won in Discord giveaway!</p>
      </div>
    `;
  } else {
    statusDiv.innerHTML = `
      <div style="margin-top: 15px; text-align: center; font-size: 14px; color: #666;">
        <strong>Free Tier:</strong> ${MAX_IMAGES_FREE - imageCount} images & ${MAX_MESSAGES_FREE - messageCount} messages left<br><br>
        <strong>Win NovaHoyaAI Pro in Discord for UNLIMITED!</strong>
      </div>
    `;
  }
}

// Unlock Pro with giveaway code
function unlockPro() {
  const code = prompt("Enter your NovaHoyaAI Pro giveaway code:");
  const validCodes = ["NOVA2026", "HOYAPRO", "ITZLOOTDEV", "DISCORDWIN", "PRO2026", "GIVEAWAY", "NOVAFIRE"]; // Add your own codes here

  if (validCodes.includes(code?.toUpperCase().trim())) {
    isPro = true;
    updateProStatus();
    saveData();
    addMessage("🎉 CONGRATS! NovaHoyaAI Pro unlocked! Unlimited images & messages + exclusive perks 🔥", "bot");
  } else if (code) {
    addMessage("Invalid code 😔 Join the Discord for giveaways: https://discord.gg/kxyFtrh9Ya", "bot");
  }
}

// Add "Win Pro" button if not Pro
if (!isPro) {
  const header = document.querySelector('header');
  const proBtn = document.createElement('button');
  proBtn.textContent = "Win NovaHoyaAI Pro 🎁";
  proBtn.style.marginTop = "15px";
  proBtn.style.padding = "14px 28px";
  proBtn.style.background = "linear-gradient(135deg, #FFD700, #FFA500)";
  proBtn.style.color = "black";
  proBtn.style.border = "none";
  proBtn.style.borderRadius = "30px";
  proBtn.style.fontWeight = "bold";
  proBtn.style.fontSize = "18px";
  proBtn.style.cursor = "pointer";
  proBtn.style.boxShadow = "0 6px 20px rgba(255,215,0,0.4)";
  proBtn.onclick = unlockPro;
  header.appendChild(proBtn);
}

function addMessage(content, type) {
  const div = document.createElement("div");
  div.className = `message ${type}`;

  if (content instanceof HTMLImageElement) {
    content.alt = "Generated by NovaHoyaAI" + (isPro ? " Pro 🔥" : "");
    content.loading = "lazy";
    content.style.maxWidth = "100%";
    content.style.borderRadius = "12px";
    content.style.marginTop = "10px";
    content.style.boxShadow = "0 4px 12px rgba(0,0,0,0.5)";
    div.appendChild(content);
  } else if (typeof content === "string") {
    if (content.startsWith("http") || content.startsWith("data:image")) {
      const img = document.createElement("img");
      img.src = content;
      img.alt = "Generated by NovaHoyaAI" + (isPro ? " Pro 🔥" : "");
      img.loading = "lazy";
      img.style.maxWidth = "100%";
      img.style.borderRadius = "12px";
      img.style.marginTop = "10px";
      div.appendChild(img);
    } else {
      if (isPro && type === "bot" && Math.random() < 0.4) {
        content += " (NovaHoyaAI Pro 🔥)";
      }
      div.innerText = content;
    }
  }

  chatArea.appendChild(div);
  chatArea.scrollTop = chatArea.scrollHeight;

  saveData();
  updateProStatus();
}

async function sendMessage() {
  const text = input.value.trim();
  if (!text) return;

  // Free user limits
  if (!isPro) {
    if (messageCount >= MAX_MESSAGES_FREE) {
      addMessage(`Message limit reached (${MAX_MESSAGES_FREE}). Win Pro in Discord for unlimited: https://discord.gg/kxyFtrh9Ya`, "bot");
      return;
    }
  }

  addMessage(text, "user");
  input.value = "";
  messageCount++;
  messages.push({ role: "user", content: text });

  const lowerText = text.toLowerCase();
  const isImageRequest = lowerText.includes("generate") || lowerText.includes("create") || 
                         lowerText.includes("draw") || lowerText.includes("image") || 
                         lowerText.includes("picture") || lowerText.includes("logo");

  if (isImageRequest) {
    if (!isPro && imageCount >= MAX_IMAGES_FREE) {
      addMessage(`Image limit reached (${MAX_IMAGES_FREE}). Win Pro in Discord for unlimited: https://discord.gg/kxyFtrh9Ya`, "bot");
      return;
    }

    const loadingDiv = document.createElement("div");
    loadingDiv.className = "message bot";
    loadingDiv.innerText = isPro ? "Generating Pro-quality image... 🔥🔥" : "Generating image... 🔥";
    chatArea.appendChild(loadingDiv);
    chatArea.scrollTop = chatArea.scrollHeight;

    try {
      const imageElement = await puter.ai.txt2img(text, {
        model: "black-forest-labs/FLUX.1-schnell"
      });
      chatArea.removeChild(loadingDiv);
      addMessage(imageElement, "bot");
      imageCount++;
    } catch (err) {
      chatArea.removeChild(loadingDiv);
      addMessage("Image generation failed — try again bro!", "bot");
    }
  } else {
    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages })
      });

      const data = await res.json();
      addMessage(data.reply, "bot");
      messages.push({ role: "assistant", content: data.reply });

    } catch (err) {
      addMessage("Error connecting to NovaHoyaAI.", "bot");
    }
  }

  saveData();
  updateProStatus();
}

sendBtn.onclick = sendMessage;
input.addEventListener("keydown", e => {
  if (e.key === "Enter") {
    e.preventDefault();
    sendMessage();
  }
});

// Intro message
addMessage("Hey! I'm NovaHoyaAI 🚀\nFree users: 5 images + 25 messages\nWin Pro in Discord for UNLIMITED: https://discord.gg/kxyFtrh9Ya", "bot");

input.focus();