const input = document.getElementById("userInput");
const sendBtn = document.getElementById("sendBtn");
const chatArea = document.getElementById("chatArea");

let messages = [
  {
    role: "system",
    content: `
You are Nova AI.
Created and owned by itzlootdev.

You are NOT ChatGPT.
You are NOT developed by OpenAI.

Your Development Name is NovaCreations.

Your Support Server In Discord is : Nova Creations, And Invite Link Is : https://discord.gg/kxyFtrh9Ya

Specialist In:
- Edge Computing
- Ultra-low latency systems
- AI & distributed systems
- Generating Images

Main CEO Of You:
 Afsal
 Ahzan 
 Ammar

Always introduce yourself as Nova AI when starting a new chat.
When generating an image, reply ONLY with the image URL or base64 (or an array if multiple).
    `
  }
];

function addMessage(content, type) {
  const div = document.createElement("div");
  div.className = `message ${type}`;

  // Handle string (text or single image URL/base64)
  if (typeof content === "string") {
    if (content.startsWith("http") || content.startsWith("data:image")) {
      // It's an image
      const img = document.createElement("img");
      img.src = content;
      img.alt = "Generated by Nova AI";
      img.loading = "lazy";
      img.style.maxWidth = "100%";
      img.style.borderRadius = "12px";
      img.style.marginTop = "10px";
      img.style.boxShadow = "0 4px 12px rgba(0,0,0,0.5)";
      div.appendChild(img);
    } else {
      // Normal text
      div.innerText = content;
    }
  }
  // Handle array (multiple images or text + images)
  else if (Array.isArray(content)) {
    content.forEach(part => {
      if (typeof part === "string") {
        if (part.startsWith("http") || part.startsWith("data:image")) {
          const img = document.createElement("img");
          img.src = part;
          img.alt = "Generated by Nova AI";
          img.loading = "lazy";
          img.style.maxWidth = "100%";
          img.style.borderRadius = "12px";
          img.style.margin = "10px 0";
          img.style.display = "block";
          div.appendChild(img);
        } else {
          div.appendChild(document.createTextNode(part));
          div.appendChild(document.createElement("br"));
        }
      }
    });
  } else {
    div.innerText = String(content);
  }

  chatArea.appendChild(div);
  chatArea.scrollTop = chatArea.scrollHeight;
}

sendBtn.onclick = sendMessage;
input.addEventListener("keydown", e => {
  if (e.key === "Enter") {
    e.preventDefault();
    sendMessage();
  }
});

async function sendMessage() {
  const text = input.value.trim();
  if (!text) return;

  addMessage(text, "user");
  input.value = "";

  messages.push({ role: "user", content: text });

  try {
    const res = await fetch("/api/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ messages })
    });

    const data = await res.json();
    addMessage(data.reply, "bot");
    messages.push({ role: "assistant", content: data.reply });

  } catch (err) {
    console.error(err);
    addMessage("Error connecting to Nova AI.", "bot");
  }
}

// Intro message on load
addMessage("Hey! I'm Nova AI 🚀 Ready to chat or generate images. Try asking me to generate something!", "bot");

input.focus();