// Elements
  const input = document.getElementById("userInput");
  const sendBtn = document.getElementById("sendBtn");
  const chatArea = document.getElementById("chatArea");

  // Message history
  let messages = [
    {
      role: "system",
      content: `
You are Nova AI.
Created and owned by itzlootdev.

You are NOT ChatGPT.
You are NOT developed by OpenAI.

Your Development Name is NovaCreations.

Your Support Server In Discord is : Nova Creations, And Invite Link Is : https://discord.gg/kxyFtrh9Ya

Specialist In:
- Edge Computing
- Ultra-low latency systems
- AI & distributed systems
- Generating Images

Main CEO Of You:
 Afsal
 Ahzan 
 Ammar

Always introduce yourself as Nova AI at the start of a new conversation.
If the user asks for an image (e.g. "generate a cat", "draw a landscape"), respond ONLY with the direct image URL (no extra text).
For normal chat, reply normally.
      `
    }
  ];

  // Add message (supports text, image URL, or array mixed)
  function addMessage(content, type) {
    const div = document.createElement("div");
    div.className = `message ${type}`;

    if (typeof content === "string") {
      if (content.startsWith("http") && (content.endsWith(".png") || content.endsWith(".jpg") || content.endsWith(".jpeg"))) {
        const img = document.createElement("img");
        img.src = content;
        img.alt = "Generated by Nova AI";
        img.loading = "lazy";
        img.style.maxWidth = "100%";
        img.style.borderRadius = "12px";
        img.style.marginTop = "8px";
        img.style.boxShadow = "0 4px 12px rgba(0,0,0,0.5)";
        div.appendChild(img);
      } else {
        div.innerText = content;
      }
    } else if (Array.isArray(content)) {
      content.forEach(part => {
        if (typeof part === "string" && part.startsWith("http") && (part.endsWith(".png") || part.endsWith(".jpg") || part.endsWith(".jpeg"))) {
          const img = document.createElement("img");
          img.src = part;
          img.alt = "Generated by Nova AI";
          img.loading = "lazy";
          img.style.maxWidth = "100%";
          img.style.borderRadius = "12px";
          img.style.margin = "8px 0";
          img.style.display = "block";
          div.appendChild(img);
        } else {
          const textNode = document.createTextNode(part + " ");
          div.appendChild(textNode);
        }
      });
    } else {
      div.innerText = String(content);
    }

    chatArea.appendChild(div);
    chatArea.scrollTop = chatArea.scrollHeight;
  }

  // Events
  sendBtn.onclick = sendMessage;
  input.addEventListener("keydown", e => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  });

  async function sendMessage() {
    const text = input.value.trim();
    if (!text) return;

    addMessage(text, "user");
    input.value = "";

    messages.push({ role: "user", content: text });

    // Simple image detection
    const lowerText = text.toLowerCase();
    const isImageRequest = lowerText.includes("generate") || lowerText.includes("image") || 
                           lowerText.includes("draw") || lowerText.includes("picture") || 
                           lowerText.includes("photo") || lowerText.includes("create an image");

    try {
      let reply;

      if (isImageRequest) {
        // Call real free Flux API (fast & high quality)
        const res = await fetch("https://api.together.xyz/v1/images/generations", {
          method: "POST",
          headers: {
            "Authorization": "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", // FREE public key for schnell-Free (no signup needed for basic use)
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            model: "black-forest-labs/FLUX.1-schnell-Free",
            prompt: text,
            width: 1024,
            height: 1024,
            steps: 4,
            n: 1,
            response_format: "url"
          })
        });

        const data = await res.json();
        reply = data.data[0].url; // direct image URL
      } else {
        // Normal chat (you can replace with your own LLM later)
        reply = "Hey bro! I'm Nova AI 🚀 I can chat or generate sick images. Just say something like 'generate a cyberpunk city' and watch it pop!";
      }

      addMessage(reply, "bot");
      messages.push({ role: "assistant", content: reply });

    } catch (err) {
      console.error(err);
      addMessage("Error: Couldn't generate right now. Try again bro!", "bot");
    }
  }

  // Auto focus
  window.onload = () => input.focus();